spring:
  datasource:
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    #username: sell
    #password: oracle
    #url: jdbc:oracle:thin:@//127.0.0.1:1521/orcl
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.79.130:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null

wechat:
  mpAppId: wxd898fcb01713c658
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: D:/developUtil/h5.p12
  notifyUrl: http://aifl.natapp1.cc/sell/pay/notify

server:
  context-path: /sell

